import type { Metadata } from "next";
import { IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from "@/context/AOS-content";
import Navbar from "@/components/Navbar/Navbar";
import LenisContext from "@/context/LenisContext";

const ibm_mono = IBM_Plex_Mono({
  variable: "--font-IBM_PIBM_Plex_Mono",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Paolo Sibua - Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${ibm_mono.variable} ${ibm_mono.className} container mx-auto max-w-[1480px]`}
      >
        <LenisContext>
          <AOSProvider>
            <Navbar />
            {children}
          </AOSProvider>
        </LenisContext>
      </body>
    </html>
  );
}
