import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import AOSProvider from "@/context/AOS-content";
import Navbar from "@/components/Navbar/Navbar";

const open_sans = Open_Sans({
  variable: "--font-open_sans",
  weight: ["300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Paolo Sibua - Personal Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${open_sans.variable} ${open_sans.className} container mx-auto max-w-[1280px]  `}
      >
        <AOSProvider>
          <Navbar />
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}
